### ISSUE TITLE
Come Up with Queries for Subscriptions Report (comment them here)

### ISSUE THREAD

**Issue by gabo0802** [gabo0802/UF-OneClick#57]
**Subscription Report is Done (at least visually) now we need to put data in it**

Here it what it looks like:
<br>
![image](https://user-images.githubusercontent.com/92041237/228663298-1c706557-49e2-4e5a-9e51-ceb78ae75802.png)
<br>

**Usability**

Users will be able to click on each entry on the accordion and it will give them output queries on what they ask for. The first one here as an example gives the subscription services sorted from the longest amount of time held to shortest.

We need query examples that we can implement for this pretty much.

**Further comments**

As a personal note, I also need to move this into its own component

**Comment by mslinger** [comment]
Potential Queries:

- Average Price of Subscriptions
- Average Age of Subscriptions

**Comment by gabo0802** [comment]
Finalized for now (can always add more in the future)
